# Generated by Django 3.1.1 on 2020-09-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20200925_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='category',
            field=models.CharField(choices=[('RS', 'Restaurant'), ('CF', 'Cafe')], default='RS', max_length=2),
        ),
    ]
