# Generated by Django 3.1.1 on 2020-09-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20200930_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ID',
            new_name='id',
        ),
    ]
