# Generated by Django 3.1.1 on 2020-10-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200930_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='user',
            new_name='owner',
        ),
    ]
